environment: dev
replicas: 1

image:
  repository: evidently/evidently
  tag: 0.4.27
  pullPolicy: IfNotPresent

prometheus:
  endpoint: http://prometheus-stack-kube-prom-prometheus.monitoring:9090

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi
