apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
  namespace: {{ .Release.Namespace }}
data:
  feature_store.yaml: |
    project: mlops_platform
    registry: gs://feast-registry/mlops_platform/registry.db
    provider: gcp
    online_store:
      type: redis
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
    offline_store:
      type: file
    entity_key_serialization_format: proto
